# ------------------------------------
# Site settings for Academicpages theme
# ------------------------------------

# Jekyll
permalink: /:collection/:path/
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

# The theme is hosted on a remote repository, so use remote_theme.
remote_theme: "academicpages/academicpages.github.io@v4.0.0"

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
