# ------------------------------------
# Site settings for Academicpages theme
# ------------------------------------

# Jekyll
permalink: /:collection/:path/
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

# Minima theme doesn't apply to this theme
theme: "jekyll-academicpages"

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
