# ------------------------------------
# Site settings for Academicpages theme
# ------------------------------------

# Jekyll
markdown: kramdown
plugins:
  - jekyll-email-protect

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
