baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

theme: minima
minima:
  skin: dark

collections:
  publications:
    output: true
  showcase:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/
